DET_SOURCE_DIR: '/home/zonepg/code/AIC22-MCVT/datasets/algorithm_results/detection/images/test/S06/'
REID_MODEL: 'reid_model/resnet101_ibn_a_3.pth'
REID_BACKBONE: 'resnet101_ibn_a'
DET_IMG_DIR: '/home/zonepg/code/AIC22-MCVT/datasets/algorithm_results/detect_merge/'
DATA_DIR: '/home/zonepg/code/AIC22-MCVT/datasets/algorithm_results/detect_reid3/'
REID_SIZE_TEST: [384, 384]
