CHALLENGE_DATA_DIR: '/home/zonepg/code/AIC22-MCVT/datasets/AIC22_Track1_MTMC_Tracking/'
DET_SOURCE_DIR: '/home/zonepg/code/AIC22-MCVT/datasets/algorithm_results/detection/images/test/S06/'
DATA_DIR: '/home/zonepg/code/AIC22-MCVT/datasets/algorithm_results/detect_merge/'
REID_SIZE_TEST: [384, 384]    # 384, 256
ROI_DIR: '/home/zonepg/code/AIC22-MCVT/datasets/AIC22_Track1_MTMC_Tracking/test/S06/'
CID_BIAS_DIR: '/home/zonepg/code/AIC22-MCVT/datasets/AIC22_Track1_MTMC_Tracking/cam_timestamp/'
USE_RERANK: True
USE_FF: True
SCORE_THR: 0.1
MCMT_OUTPUT_TXT: 'track1.txt'
